//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Data {
    
    private DataPair[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pair", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DataPair[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DataPair {
    
    private DataPairDataLine[] dataLineField;
    
    private string indexField;
    
    private string legendNameOfXAxisField;
    
    private string legendNameOfYAxisField;
    
    private string graphTitleField;
    
    private string scaleOfXAxisField;
    
    private string scaleOfYAxisField;
    
    private string maximumOfXField;
    
    private string minimunOfXField;
    
    private string maximumOfYField;
    
    private string minimumOfYField;
    
    private string majorOfXAxisField;
    
    private string minorOfXAxisField;
    
    private string majorOfYAxisField;
    
    private string minorOfYAxisField;
    
    private string headerTextField;
    
    private string footerTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DataPairDataLine[] DataLine {
        get {
            return this.dataLineField;
        }
        set {
            this.dataLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LegendNameOfXAxis {
        get {
            return this.legendNameOfXAxisField;
        }
        set {
            this.legendNameOfXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LegendNameOfYAxis {
        get {
            return this.legendNameOfYAxisField;
        }
        set {
            this.legendNameOfYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GraphTitle {
        get {
            return this.graphTitleField;
        }
        set {
            this.graphTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ScaleOfXAxis {
        get {
            return this.scaleOfXAxisField;
        }
        set {
            this.scaleOfXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ScaleOfYAxis {
        get {
            return this.scaleOfYAxisField;
        }
        set {
            this.scaleOfYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaximumOfX {
        get {
            return this.maximumOfXField;
        }
        set {
            this.maximumOfXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinimunOfX {
        get {
            return this.minimunOfXField;
        }
        set {
            this.minimunOfXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaximumOfY {
        get {
            return this.maximumOfYField;
        }
        set {
            this.maximumOfYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinimumOfY {
        get {
            return this.minimumOfYField;
        }
        set {
            this.minimumOfYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MajorOfXAxis {
        get {
            return this.majorOfXAxisField;
        }
        set {
            this.majorOfXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinorOfXAxis {
        get {
            return this.minorOfXAxisField;
        }
        set {
            this.minorOfXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MajorOfYAxis {
        get {
            return this.majorOfYAxisField;
        }
        set {
            this.majorOfYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinorOfYAxis {
        get {
            return this.minorOfYAxisField;
        }
        set {
            this.minorOfYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderText {
        get {
            return this.headerTextField;
        }
        set {
            this.headerTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FooterText {
        get {
            return this.footerTextField;
        }
        set {
            this.footerTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DataPairDataLine {
    
    private string indexField;
    
    private string xDataField;
    
    private string dataRowField;
    
    private string startDataColumnField;
    
    private string endDataColumnField;
    
    private string colorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string XData {
        get {
            return this.xDataField;
        }
        set {
            this.xDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataRow {
        get {
            return this.dataRowField;
        }
        set {
            this.dataRowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StartDataColumn {
        get {
            return this.startDataColumnField;
        }
        set {
            this.startDataColumnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EndDataColumn {
        get {
            return this.endDataColumnField;
        }
        set {
            this.endDataColumnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
}
